language: generic

notifications: # set notification options
  email:
    recipients:
      - mahammad.ali01@sap.com
    
    # change is when the repo status goes from pass to fail or vice versa
    on_success: [always]
    on_failure: [always]
    

# whitelist
branches:
  only:
    - master
    - working
    - feaure
    - revert 

    - new feature
